### ISSUE TITLE
`pic` should take an image and not a path.

### ISSUE THREAD

**Issue by Dherse** [dei-layborer/o-rly-typst#1]
Due to the way typst handles paths, if you use a string for the path, it will always try and get an image within the local copy of the package instead of inside of the user's project. This can be fixed by making `pic` an image or a byte array (i.e `read("my_file.png")` and using `image.decode`)

**Comment by dei-layborer** [comment]
Good catch, as unfortunately there's not really any way to test how something will behave before it's uploaded to universe.  However, changing to ``read()`` wouldn't resolve the issue, as according to the docs, paths work the same way with that function as they do with ``image()``.

I'm submitting a change using what *should* be an absolute path to the project root, so we'll see how that goes.

**Comment by dei-layborer** [comment]
I had unfortunately sat on this for a bit, but thankfully @jneug came through with a fix.  It's been merged into this repo, so I just need to make a couple tweaks to the README and I'll make a pull request to Universe to get it merged over there.  Thanks very much for bringing the issue to my attention, and sorry it took so long to address.  The changes will hopefully be on Universe soon!
